apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cmName }}
  namespace: {{ .Values.namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
data:
{{- range $key, $value := .Values.cmdata }}
  {{ $key }}: {{ $value | quote }}
{{- end }}