apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: {{ .Values.secretName }}
type: {{ .Values.secretType }}
data:
{{- range $key, $value := .Values.secretdata }}
  {{ $key }}: {{ $value }}
{{- end }}