# HISTORY
# echo -n  "http://minio-service.minio.svc.cluster.local:9000" | base64
# echo -n "minio" | base64
# echo -n "minio123" | base64
# echo -n "None" | base64
# echo -n "models" | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: minio
type: Opaque
data:
  MINIO_ACCESS_KEY_ID: bWluaW8=
  MINIO_DEFAULT_REGION: Tm9uZQ==
  MINIO_S3_BUCKET: bW9kZWxz
  MINIO_S3_ENDPOINT: aHR0cDovL21pbmlvLXNlcnZpY2UubWluaW8uc3ZjLmNsdXN0ZXIubG9jYWw6OTAwMA==
  MINIO_SECRET_ACCESS_KEY: bWluaW8xMjM=