apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "data-science-project for {{ .Values.namespace }}"
    openshift.io/display-name: "{{ .Values.namespace }}"
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace }}
    modelmesh-enabled: "true"
    opendatahub.io/dashboard: "true"
  name: {{ .Values.namespace }}
  