# Manually create
# Make sure you have 3 workers node for block storage
---
kind: StorageSystem
apiVersion: odf.openshift.io/v1alpha1
metadata:
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: ocs-storagecluster
  namespace: openshift-storage