apiVersion: v1
kind: Namespace
metadata:
  name: openshift-distributed-tracing
---
apiVersion: operators.coreos.com/v1
kind: Operator
metadata:
  name: jaeger-product.openshift-distributed-tracing
---
apiVersion: operators.coreos.com/v1
kind: Operator
metadata:
  name: kiali-ossm.openshift-operators

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/jaeger-product.openshift-distributed-tracing: ""
  name: jaeger-product
  namespace: openshift-distributed-tracing
spec:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: jaeger-operator.v1.53.0-3
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kiali-ossm.openshift-operators: ""
  name: kiali-ossm
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: kiali-operator.v1.65.11



