apiVersion: operators.coreos.com/v1
kind: Operator
metadata:
  name: devworkspace-operator.openshift-operators

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  # annotations:
  #   olm.generated-by: install-228g4
  labels:
    olm.managed: "true"
    operators.coreos.com/devworkspace-operator.openshift-operators: ""
  name: devworkspace-operator-fast-redhat-operators-openshift-marketplace
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: devworkspace-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: devworkspace-operator.v0.25.0
