#oc get acceleratorprofiles.dashboard.opendatahub.io nvidia-gpu -n redhat-ods-applications -o yaml | oc neat
apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  name: nvidia-gpu
  namespace: redhat-ods-applications
spec:
  displayName: Nvidia GPU
  enabled: true
  identifier: nvidia.com/gpu
