apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "131072"
    machine.openshift.io/vCPU: "32"
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-fnth8-nm6ss
  name: cluster-fnth8-nm6ss-worker-us-east-2b
  namespace: openshift-machine-api
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-fnth8-nm6ss
      machine.openshift.io/cluster-api-machineset: cluster-fnth8-nm6ss-worker-us-east-2b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-fnth8-nm6ss
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-fnth8-nm6ss-worker-us-east-2b
    spec:
      providerSpec:
        value:
          ami:
            id: ami-01af87a6ecc18023d
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: 100
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-fnth8-nm6ss-worker-profile
          instanceType: m5.8xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-fnth8-nm6ss-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-fnth8-nm6ss-private-us-east-2b
          tags:
          - name: kubernetes.io/cluster/cluster-fnth8-nm6ss
            value: owned
          - name: Stack
            value: project ocp4-cluster-fnth8
          - name: env_type
            value: ocp4-cluster
          - name: guid
            value: fnth8
          - name: owner
            value: unknown
          - name: platform
            value: rhpds
          - name: uuid
            value: 922f77f3-0836-5b89-b029-71c9d78033a3
          userDataSecret:
            name: worker-user-data
